spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: 12345
    driverClassName: com.mysql.cj.jdbc.Driver
    
mybatis:
  #config-location: classpath:mybatis/config.xml
  mapper-locations:
  - classpath:mybatis/mapper.xml