spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: 12345
    driverClassName: com.mysql.cj.jdbc.Driver
    
mybatis:
  #config-location: classpath:mybatis/config.xml
  mapper-locations:
  - classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    
pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致